"""
robots_txt.py
-------------
Generates a 2026 "maximum AI visibility" robots.txt for a brand that sells
products/services (not a publisher protecting IP). It explicitly ALLOWS every
major search/retrieval + user-fetch AI agent, keeps private paths blocked for
all bots, and references the sitemap + llms.txt.

Note: robots.txt is advisory. A few crawlers (e.g. Bytespider) ignore it, so
for true control you also need server/WAF rules — but for visibility this file
is the right lever.
"""

from __future__ import annotations

ALLOW_BOTS = [
    ("# OpenAI / ChatGPT", ["GPTBot", "OAI-SearchBot", "ChatGPT-User"]),
    ("# Anthropic / Claude", ["ClaudeBot", "Claude-User", "Claude-SearchBot"]),
    ("# Perplexity", ["PerplexityBot", "Perplexity-User"]),
    ("# Google generative (Gemini / AI Overviews)", ["Google-Extended"]),
    ("# Apple Intelligence", ["Applebot-Extended"]),
    ("# Microsoft / Bing (feeds ChatGPT retrieval)", ["bingbot"]),
]

PRIVATE_PATHS = ["/admin/", "/wp-admin/", "/cart/", "/checkout/", "/account/", "/api/", "/private/"]


def generate(domain: str) -> str:
    domain = domain.rstrip("/")
    out: list[str] = []
    out.append("# robots.txt — maximum AI + search visibility (generated by visibility-engine)")
    out.append("# Posture: brand selling services -> allow AI bots, block only private paths.\n")

    out.append("User-agent: *")
    out.append("Allow: /")
    for p in PRIVATE_PATHS:
        out.append(f"Disallow: {p}")
    out.append("")

    for comment, bots in ALLOW_BOTS:
        out.append(comment)
        for bot in bots:
            out.append(f"User-agent: {bot}")
            out.append("Allow: /")
        out.append("")

    out.append(f"Sitemap: {domain}/sitemap.xml")
    out.append(f"Sitemap: {domain}/llms.txt")
    return "\n".join(out) + "\n"
